### ISSUE TITLE
Lenovo thinkbook 15 g4 

### ISSUE THREAD

**Issue by taygun08** [xuwd1/lenovo-legion-slim7i-gen7-knowledges#1]
Hello, https://github.com/xuwd1/lenovo-legion-slim7i-gen7-knowledges/wiki/ you have given a solution for 10a5:9800 here.
My computer model is different, but the fingerprint hardware we use is the same.
Below I leave the error I received and a few information that I think is necessary. I would be very happy if you can help :)
#<->#
`yay -Sy libfprint-fpcmoh-git`
Error:
`==> prepare() işlemine başlanıyor...
hata: yama başarısız oldu: libfprint/meson.build:141
hata: libfprint/meson.build: yama uygulanamıyor
hata: yama başarısız oldu: meson.build:126
hata: meson.build: yama uygulanamıyor
==> HATA: prepare() içinde bir hata oluştu.
    Çıkılıyor...
 -> yapılırken hata: libfprint-fpcmoh-git-exit status 4
 -> İstenen paketler yüklenemedi. Manüel müdahale gerekli:
libfprint-fpcmoh-git - exit status 4`
#<->#
`lsusb`
Output:
`Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 003 Device 002: ID 30c9:0030 Luxvisions Innotech Limited Integrated Camera
Bus 003 Device 003: ID 10a5:9800 FPC FPC Sensor Controller L:0002 FW:25.26.23.19
Bus 003 Device 004: ID 0bda:4853 Realtek Semiconductor Corp. Bluetooth Radio
Bus 003 Device 005: ID 346d:5678 USB Disk 2.0
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
`
#<->#
`uname -m && uname -r && uname -s && uname -v`
Output:
`x86_64
6.6.1-arch1-1
Linux
#1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000`

**Comment by xuwd1** [comment]
> Hello, https://github.com/xuwd1/lenovo-legion-slim7i-gen7-knowledges/wiki/ you have given a solution for 10a5:9800 here.
> My computer model is different, but the fingerprint hardware we use is the same.
> Below I leave the error I received and a few information that I think is necessary. I would be very happy if you can help :)
> #<->#
> `yay -Sy libfprint-fpcmoh-git`
> Error:
> `==> prepare() işlemine başlanıyor... hata: yama başarısız oldu: libfprint/meson.build:141 hata: libfprint/meson.build: yama uygulanamıyor hata: yama başarısız oldu: meson.build:126 hata: meson.build: yama uygulanamıyor ==> HATA: prepare() içinde bir hata oluştu. Çıkılıyor... -> yapılırken hata: libfprint-fpcmoh-git-exit status 4 -> İstenen paketler yüklenemedi. Manüel müdahale gerekli: libfprint-fpcmoh-git - exit status 4`
> #<->#
> `lsusb`
> Output:
> `Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub Bus 003 Device 002: ID 30c9:0030 Luxvisions Innotech Limited Integrated Camera Bus 003 Device 003: ID 10a5:9800 FPC FPC Sensor Controller L:0002 FW:25.26.23.19 Bus 003 Device 004: ID 0bda:4853 Realtek Semiconductor Corp. Bluetooth Radio Bus 003 Device 005: ID 346d:5678 USB Disk 2.0 Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub `
> #<->#
> `uname -m && uname -r && uname -s && uname -v`
> Output:
> `x86_64 6.6.1-arch1-1 Linux #1 SMP PREEMPT_DYNAMIC Wed, 08 Nov 2023 16:05:38 +0000`

Hi, sorry for being late, and thanks for pointing out this problem. It seems like the PKGBUILD script is having trouble patching the meson.build file, presumably due to the libfprint has its meson.build updated. I will try to fix this in the near future.

**Comment by taygun08** [comment]
I would appreciate it if you let me know here when you release the update. Thank you <3

**Comment by xuwd1** [comment]
> I would appreciate it if you let me know here when you release the update. Thank you <3

Sure, the AUR package `libfprint-fpcmoh-git` has been updated and should be working now, please check it.

**Comment by taygun08** [comment]
apparently it works thank you :)
